### ISSUE TITLE
30th sept, Wednesday data missing

### ISSUE THREAD

**Issue by OrkoHunter** [kgpmnc/blog#1]
- [x] BS
- [x] EVS
- [x] Algo (1 class)

**Comment by shubhamtibra** [comment]
BS: Nervous system taught and there will be no question in end sem from this topic. no attendance taken.
EVS: Air pollution, attendance taken.

**Comment by OrkoHunter** [comment]
Thanks @shubhamtibra @shivam1996 :)

**Comment by kshitij10496** [comment]
@OrkoHunter We finally have a new contributor among us @shubhamtibra
